# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 09:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('dateOfBirth', models.DateField(default=datetime.date(2016, 10, 2))),
                ('telephone', models.PositiveIntegerField(blank=True, default=1)),
                ('mobile', models.PositiveIntegerField(blank=True, default=1)),
                ('profession', models.PositiveIntegerField(choices=[(1, 'Doctor'), (2, 'Unemployed')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
