# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceBroker',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.Account')),
                ('afm', models.PositiveIntegerField(default=' ')),
            ],
            options={
                'abstract': False,
            },
            bases=('authentication.account',),
        ),
        migrations.CreateModel(
            name='Insured',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.Account')),
                ('afm', models.PositiveIntegerField(default=' ')),
                ('amka', models.PositiveIntegerField(default=' ')),
            ],
            options={
                'abstract': False,
            },
            bases=('authentication.account',),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveIntegerField(choices=[(1, 'IX'), (2, 'EIX')])),
                ('brand', models.PositiveIntegerField(choices=[(1, 'Opel'), (2, 'Citroen')])),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[(1, 'Opel'), (2, 'Citroen')], default=' ', max_length=20)),
            ],
        ),
    ]
