# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='model',
            field=models.PositiveIntegerField(choices=[((1, 'Corsa'), (2, 'Vectra')), ((1, 'C3'), (2, 'C4'))], default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='brand',
            field=models.PositiveIntegerField(choices=[(1, 'Opel'), (2, 'Citroen')], default=' ', max_length=20),
        ),
    ]
