# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySurance', '0002_auto_20161002_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancebroker',
            name='afm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insured',
            name='afm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insured',
            name='amka',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.PositiveIntegerField(choices=[(1, 'IX'), (2, 'EIX')], default=0),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='brand',
            field=models.PositiveIntegerField(choices=[(1, 'Opel'), (2, 'Citroen')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='model',
            field=models.PositiveIntegerField(choices=[((1, 'Corsa'), (2, 'Vectra')), ((1, 'C3'), (2, 'C4'))], default=0, max_length=100),
        ),
    ]
